
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: image_storage
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask-app:
    build: ./BE
    container_name: flask-app
    restart: always
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      - postgres
    volumes:
      - ./BE/app.py:/app/app.py  #
  # web:
  #   build: ./web
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./web/src:/app/src  #
  rtsp_to_web:
    build: ./RTSPtoWeb
    ports:
      - "8083:8083"


volumes:
  postgres_data:
